apiVersion: v1
kind: Namespace
metadata:
  name: $SERVICE_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
  namespace: $SERVICE_NAME
  labels:
    app: $SERVICE_NAME
spec:
  ports:
  - port: $SERVICE_PORT
    targetPort: $SERVICE_PORT
  selector:
    app: $SERVICE_NAME
---
apiVersion: v1
kind: Secret
metadata:
  name: $SERVICE_NAME
  namespace: $SERVICE_NAME
type: Opaque
data:
  mongoHost: bW9uZ29kYitzcnY6Ly9lc2FzZTpUZXJtaW5hdG9yMTZAdGVzdGNsdXN0ZXIueG94eGdubS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE_NAME
  namespace: $SERVICE_NAME
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: $SERVICE_NAME
  template:
    metadata:
      namespace: $SERVICE_NAME
      labels:
        app: $SERVICE_NAME
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "$SERVICE_PORT"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: $SERVICE_NAME
        image: $IMAGE_NAME
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_HOST
          valueFrom:
              secretKeyRef:
                name: $SERVICE_NAME
                key: mongoHost
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $SERVICE_NAME
  namespace: $SERVICE_NAME
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /$SERVICE_NAME(/|$)(.*)
        backend:
          service:
            name: $SERVICE_NAME
            port:
              number: $SERVICE_PORT
---